/* JavaLogic — Coding Questions bank (ST-1 syllabus, module-wise)
   Format: { m:module(1-6), name:program name, logic:approach/steps }
*/
const CODING = [
// ===== Module 1: Basics — data types, variables, operators, simple I/O =====
{m:1,name:"Do numbers ka sum",logic:"Do int variables a, b lo (Scanner se input). sum = a + b karo aur print kar do. Basic arithmetic + operator ka use."},
{m:1,name:"Rectangle ka area aur perimeter",logic:"length aur breadth input lo. area = length*breadth, perimeter = 2*(length+breadth). Dono print karo."},
{m:1,name:"Circle ka area aur circumference",logic:"radius input lo. final double PI=3.14159 lo. area = PI*r*r, circumference = 2*PI*r. Print karo."},
{m:1,name:"Simple Interest nikaalo",logic:"principal p, rate r, time t input lo. SI = (p*r*t)/100. Result print karo."},
{m:1,name:"Do numbers swap karo (temp variable se)",logic:"temp = a; a = b; b = temp; ke through values exchange karo. Pehle aur baad ki values print karo."},
{m:1,name:"Do numbers swap karo (bina temp ke)",logic:"a = a + b; b = a - b; a = a - b; se swap karo. (Ya XOR se: a=a^b; b=a^b; a=a^b;)."},
{m:1,name:"Celsius ko Fahrenheit me badlo",logic:"celsius input lo. f = (celsius * 9/5) + 32. Dhyan: 9.0/5 use karo warna int division galat dega."},
{m:1,name:"Seconds ko hours:minutes:seconds me badlo",logic:"totalSec input lo. h = totalSec/3600; m = (totalSec%3600)/60; s = totalSec%60. Teeno print karo."},
{m:1,name:"Teen numbers ka average",logic:"a, b, c input lo. avg = (a + b + c) / 3.0 (float division ke liye 3.0). Print karo."},
{m:1,name:"Number ka square aur cube",logic:"n input lo. square = n*n, cube = n*n*n. Print karo."},
{m:1,name:"Number ka last digit nikaalo",logic:"n input lo. lastDigit = n % 10 se aakhri digit milta hai. Print karo."},
{m:1,name:"Total marks aur percentage",logic:"5 subjects ke marks input lo. total = sabhi ka sum. percentage = (total/500.0)*100. Print karo."},
{m:1,name:"Even ya Odd (operator se)",logic:"n input lo. Agar n%2==0 to even, warna odd. Yahan modulus operator ka use hota hai."},
{m:1,name:"ASCII value nikaalo",logic:"ek char input lo. int me cast karo: int ascii = (int) ch; Print ascii value."},
{m:1,name:"Distance = speed * time",logic:"speed aur time input lo. distance = speed * time. Simple formula-based program."},

// ===== Module 2: Control statements, loops, patterns =====
{m:2,name:"Teen numbers me sabse bada",logic:"a,b,c lo. if-else if se compare: agar a>=b && a>=c to a bada; else if b>=c to b; else c. Nested/ladder if ka use."},
{m:2,name:"Number positive, negative ya zero",logic:"n lo. if(n>0) positive; else if(n<0) negative; else zero. if-else-if ladder."},
{m:2,name:"Leap year check",logic:"year lo. Agar (year%4==0 && year%100!=0) || (year%400==0) to leap year, warna nahi."},
{m:2,name:"Grade calculator (marks se)",logic:"marks lo. if-else ladder: >=90 A, >=80 B, >=70 C, >=60 D, warna F. Grade print karo."},
{m:2,name:"Vowel ya consonant",logic:"ek letter lo. Agar a/e/i/o/u (chhota/bada) me se koi ho to vowel, warna consonant. switch ya if se."},
{m:2,name:"Simple calculator (switch)",logic:"do numbers aur operator (+,-,*,/) lo. switch(op) me har case me operation karke result print karo. default me invalid."},
{m:2,name:"1 se N tak numbers print",logic:"for(i=1; i<=n; i++) loop me i print karo. Basic loop."},
{m:2,name:"1 se N tak natural numbers ka sum",logic:"sum=0; for(i=1;i<=n;i++) sum+=i; Print sum. (Ya formula n*(n+1)/2)."},
{m:2,name:"Multiplication table of N",logic:"n lo. for(i=1;i<=10;i++) print n + ' x ' + i + ' = ' + (n*i). Loop se table."},
{m:2,name:"Factorial of a number",logic:"fact=1; for(i=1;i<=n;i++) fact*=i; Print fact. (0 ka factorial 1 hota hai)."},
{m:2,name:"Number reverse karo",logic:"rev=0; while(n>0){ rev = rev*10 + n%10; n=n/10; } Print rev. Digit-by-digit reverse."},
{m:2,name:"Number me digits count karo",logic:"count=0; while(n>0){ count++; n=n/10; } Print count. Har baar /10 se ek digit hatti hai."},
{m:2,name:"Digits ka sum",logic:"sum=0; while(n>0){ sum += n%10; n=n/10; } Print sum. Har digit ko jodte jao."},
{m:2,name:"Palindrome number check",logic:"Original save karo. rev banao (rev*10 + n%10 loop me). Agar rev == original to palindrome."},
{m:2,name:"Fibonacci series (N terms)",logic:"a=0,b=1. n terms tak loop: print a; next=a+b; a=b; b=next. Har term pichhle do ka sum."},
{m:2,name:"Prime number check",logic:"n>1 hona chahiye. for(i=2;i<=n/2;i++) agar n%i==0 to prime nahi (flag=false, break). Warna prime."},
{m:2,name:"1 se N tak prime numbers",logic:"Bahar loop 2..n, andar har number ke liye prime check karo. Prime ho to print. Nested loop."},
{m:2,name:"Armstrong number check",logic:"3-digit ke liye: har digit ka cube jodo (n%10 ka cube, phir /10). Agar sum == original to Armstrong (jaise 153)."},
{m:2,name:"Perfect number check",logic:"1..n-1 tak jo divisors hain unka sum nikaalo. Agar sum == n to perfect number (jaise 6, 28)."},
{m:2,name:"GCD / HCF of two numbers",logic:"Euclid: while(b!=0){ temp=b; b=a%b; a=temp; } a hi GCD hai. (Ya loop se common divisor)."},
{m:2,name:"LCM of two numbers",logic:"Pehle GCD nikaalo. LCM = (a*b)/GCD. Print LCM."},
{m:2,name:"Power of a number (a^b)",logic:"result=1; for(i=1;i<=b;i++) result*=a; Print result. (Bina Math.pow ke)."},
{m:2,name:"Range me even aur odd ka sum",logic:"Loop 1..n. Agar i%2==0 to evenSum me jodo warna oddSum me. Dono print karo."},
{m:2,name:"Right-angled star triangle pattern",logic:"Bahar loop rows (1..n), andar loop stars (1..i), '*' print, har row ke baad newline. Nested loop."},
{m:2,name:"Pyramid star pattern",logic:"Har row me pehle spaces (n-i), phir stars (2*i-1) print karo. Center-aligned pyramid."},
{m:2,name:"Floyd's triangle (numbers)",logic:"num=1. Bahar loop rows, andar loop columns (1..i), num print karke num++. Continuous numbering."},
{m:2,name:"Number pattern (1,12,123...)",logic:"Bahar loop rows(1..n), andar loop j(1..i) me j print karo, row ke baad newline."},
{m:2,name:"Sum of series 1+2+3+...+N",logic:"Loop se sum karo ya formula n*(n+1)/2 se seedha result nikaalo."},
{m:2,name:"Count even digits in a number",logic:"while(n>0){ d=n%10; if(d%2==0) count++; n/=10; } Print count."},
{m:2,name:"Largest digit in a number",logic:"max=0; while(n>0){ d=n%10; if(d>max) max=d; n/=10; } Print max digit."},

// ===== Module 3: Methods & parameter passing =====
{m:3,name:"Method: do numbers ka sum return karo",logic:"int add(int a,int b){ return a+b; } main me call karke result print. Method + return value."},
{m:3,name:"Method: factorial return karo",logic:"int fact(int n){ f=1; loop i=1..n f*=i; return f; } main se call."},
{m:3,name:"Method: do numbers ka maximum",logic:"int max(int a,int b){ return a>b?a:b; } Ternary ya if se, value return."},
{m:3,name:"Method: prime check (boolean return)",logic:"boolean isPrime(int n){ loop 2..n/2, divisible ho to return false; end me return true; } main me if se print."},
{m:3,name:"Method: even check (boolean)",logic:"boolean isEven(int n){ return n%2==0; } Direct boolean return karke print."},
{m:3,name:"Recursion: factorial",logic:"int fact(int n){ if(n<=1) return 1; return n*fact(n-1); } Base case + khud ko call."},
{m:3,name:"Recursion: Fibonacci nth term",logic:"int fib(int n){ if(n<=1) return n; return fib(n-1)+fib(n-2); } Do recursive calls."},
{m:3,name:"Recursion: digits ka sum",logic:"int sum(int n){ if(n==0) return 0; return n%10 + sum(n/10); } Har call me ek digit."},
{m:3,name:"Recursion: power (a^b)",logic:"int power(int a,int b){ if(b==0) return 1; return a*power(a,b-1); }"},
{m:3,name:"Method overloading: area nikaalo",logic:"area(int side) square ke liye, area(int l,int b) rectangle ke liye, area(double r) circle ke liye. Same naam, alag parameters."},
{m:3,name:"Method: number reverse karo",logic:"int reverse(int n){ rev=0; while(n>0){ rev=rev*10+n%10; n/=10; } return rev; }"},
{m:3,name:"Method: swap dikhana (pass-by-value)",logic:"swap(int a,int b) me values badlo par main me original nahi badalta — Java pass-by-value hai. Isse concept clear hota hai."},
{m:3,name:"Method: array ka sum return karo",logic:"int sum(int[] arr){ s=0; for(x:arr) s+=x; return s; } Array reference pass hota hai."},
{m:3,name:"Method: number even/odd check karke message return",logic:"String check(int n){ return (n%2==0)?\"Even\":\"Odd\"; } String return ka example."},

// ===== Module 4: Arrays & Strings =====
{m:4,name:"Array elements ka sum",logic:"Array input lo. sum=0; for-each ya for loop se sabhi elements jodo. Print sum."},
{m:4,name:"Array me largest aur smallest",logic:"max=min=arr[0] lo. Loop me har element ko compare: bada ho to max update, chhota ho to min update."},
{m:4,name:"Array ka average",logic:"Sum nikaalo, phir avg = sum / (double)arr.length. Print average."},
{m:4,name:"Array ko reverse karo",logic:"Do pointer: start=0, end=length-1. Swap karke start++ aur end-- jab tak start<end. Ya reverse loop me print."},
{m:4,name:"Linear Search",logic:"Target lo. Array me loop karke har element se compare. Match mile to index print + break; na mile to 'not found'."},
{m:4,name:"Binary Search (sorted array)",logic:"low=0, high=n-1. mid=(low+high)/2. Agar arr[mid]==key mil gaya; key bada to low=mid+1; chhota to high=mid-1. Loop while low<=high."},
{m:4,name:"Bubble Sort",logic:"Nested loop. Har pass me adjacent elements compare karo, bada ho to swap. Sabse bada element end me chala jaata hai."},
{m:4,name:"Selection Sort",logic:"Har position ke liye baaki array me minimum dhoondo, phir current position se swap karo."},
{m:4,name:"Array me even aur odd count",logic:"Loop me har element check: i%2==0 to evenCount++ warna oddCount++. Dono print."},
{m:4,name:"Array me second largest",logic:"first=second=MIN. Loop: agar element>first to second=first, first=element; else if element>second to second=element."},
{m:4,name:"Array elements ki frequency (count occurrences)",logic:"Nested loop ya count array se har element kitni baar aaya wo ginto. Visited elements ko skip karo."},
{m:4,name:"Do arrays merge karo",logic:"Naya array size (n1+n2) banao. Pehle array1 ke elements copy karo, phir array2 ke. Print merged array."},
{m:4,name:"Matrix addition (2D array)",logic:"Do matrices same size. Nested loop me c[i][j] = a[i][j] + b[i][j]. Result matrix print."},
{m:4,name:"Matrix multiplication",logic:"Teen nested loops. c[i][j] += a[i][k]*b[k][j]. Rows of A x columns of B."},
{m:4,name:"Matrix transpose",logic:"t[j][i] = m[i][j] nested loop me. Rows aur columns interchange ho jaate hain."},
{m:4,name:"String ki length (bina length() ke)",logic:"charAt() ko loop me try karo aur count karo, ya toCharArray() ki length. Count print."},
{m:4,name:"String reverse karo",logic:"Aakhir se pehle tak loop karke charAt(i) jodo, ya StringBuilder(s).reverse(). Reversed string print."},
{m:4,name:"String palindrome check",logic:"String ko reverse karo, phir equals() se compare. Ya do pointer (start/end) se characters match karo."},
{m:4,name:"Vowels aur consonants count",logic:"Loop me har char lowercase karke check: vowel ho to vCount++, agar letter hai par vowel nahi to cCount++."},
{m:4,name:"String me words count",logic:"Spaces gino: words = spaces + 1 (agar string empty na ho). Ya split(\" \").length use karo."},
{m:4,name:"Uppercase ko lowercase (aur ulta)",logic:"toUpperCase() / toLowerCase() method use karo, ya ASCII +/- 32 se manually convert."},
{m:4,name:"String ka case toggle karo",logic:"Har char check: upper ho to lower banao, lower ho to upper. Character.isUpperCase() se pata karo."},
{m:4,name:"Character ka occurrence count",logic:"Ek char aur string lo. Loop me charAt(i)==target hone par count++. Print count."},
{m:4,name:"String se spaces remove karo",logic:"Loop me har char check, space na ho to result me jodo. Ya replace(\" \",\"\")."},
{m:4,name:"Do strings anagram check",logic:"Dono ki length same ho, phir dono ke chars sort karke ya frequency count karke compare karo."},
{m:4,name:"Array me element ka index find karo",logic:"Loop me target se compare, match par index return/print, na mile to -1."},
{m:4,name:"Array me duplicate elements find karo",logic:"Nested loop: arr[i]==arr[j] (i<j) ho to duplicate print. Ya frequency count se."},

// ===== Module 5: Classes, Objects, Constructors, this =====
{m:5,name:"Student class (roll, name, marks) display",logic:"Class me 3 fields. Parameterized constructor se values set karo (this use karke). display() method se print. main me object banao."},
{m:5,name:"Rectangle class — area (constructor se)",logic:"length, breadth fields. Constructor me values lo. area() method length*breadth return kare. Object banake call."},
{m:5,name:"Bank Account (deposit/withdraw)",logic:"balance field. deposit(amt) me balance+=amt. withdraw(amt) me agar balance>=amt to minus karo warna message. display() se balance."},
{m:5,name:"Employee class (parameterized constructor)",logic:"id, name, salary fields. Constructor me this.id=id etc. show() method se details print."},
{m:5,name:"Constructor overloading example",logic:"Ek no-arg constructor default values de, ek parameterized constructor diye gaye values le. Same class me dono."},
{m:5,name:"Copy constructor example",logic:"Ek constructor jo dusre object ko parameter le aur uski fields naye object me copy kare: this.x = obj.x."},
{m:5,name:"this keyword — naming clash solve",logic:"Constructor parameter aur instance variable ka naam same. this.name = name; se object ka variable set hota hai."},
{m:5,name:"Circle class — area aur circumference",logic:"radius field, constructor se set. area()=PI*r*r, circumference()=2*PI*r. Object banake dono call."},
{m:5,name:"Complex number addition (objects se)",logic:"real, imag fields. add(Complex c) method naya Complex return kare jisme real+c.real, imag+c.imag. Objects se add."},
{m:5,name:"Do points ke beech distance",logic:"Point class me x,y. distance(Point p) me Math.sqrt((x-p.x)^2 + (y-p.y)^2). Do object banake call."},
{m:5,name:"Box class — volume (constructor)",logic:"length, width, height fields, constructor se set. volume() = l*w*h return kare. Object banake print."},
{m:5,name:"Multiple objects banake data dikhana",logic:"Ek class ke 2-3 objects banao, alag-alag constructor values do, sabka display() call karke dikhao ki har object ka data alag hai."},

// ===== Module 6: Static members & blocks =====
{m:6,name:"Static variable se object count karo",logic:"static int count field. Constructor me count++ karo. Har object banne par count badhega. ClassName.count print."},
{m:6,name:"Static method — square nikaalo",logic:"static int square(int n){ return n*n; } Bina object banaye ClassName.square(5) se call."},
{m:6,name:"Static block demonstration",logic:"static{ } block class load hote hi (main se pehle) ek baar chalta hai. Usme static variable initialize karke dikhao order."},
{m:6,name:"Static counter for instances",logic:"static int objCount=0. Constructor me objCount++. Kai objects banao, phir total count print karke shared behaviour dikhao."},
{m:6,name:"Static final constant (PI) ka use",logic:"static final double PI=3.14159. Circle area me use karo. Constant ki value change nahi hoti."},
{m:6,name:"Static method se sum (utility)",logic:"static int add(int a,int b){ return a+b; } Utility method jise object ke bina ClassName.add() se call karte hain."},
{m:6,name:"Static vs non-static variable farak",logic:"Ek static aur ek instance variable rakho. Do objects me instance alag rehta hai, static sabme shared — print karke dikhao."},
{m:6,name:"Static block + constructor order",logic:"static block, phir constructor me print statement rakho. Run karke dikhao static block sabse pehle (ek baar) chalta hai."}
];
