/* JavaLogic — MCQ Test question bank (150 questions)
   Format: { m:module(1-6), q:question, o:[options], a:correctIndex, e:explanation }
*/
const MCQS = [
// ===== Module 1: Java Basics, JDK/JRE/JVM, Data Types, Operators =====
{m:1,q:"Java program compile hone par source code kis form me convert hota hai?",o:["Machine code","Bytecode (.class)","Assembly code","Binary image"],a:1,e:"javac source (.java) ko bytecode (.class) me badalta hai, jise JVM chalati hai."},
{m:1,q:"JVM ka full form kya hai?",o:["Java Verified Machine","Java Virtual Machine","Java Variable Method","Joint Virtual Machine"],a:1,e:"JVM = Java Virtual Machine."},
{m:1,q:"Bytecode (.class) ko execute kaun karta hai?",o:["javac","JVM","JDK","OS seedha"],a:1,e:"JVM bytecode ko execute karti hai."},
{m:1,q:"Source code ko bytecode me kaun convert karta hai?",o:["JVM","JRE","javac compiler","Class loader"],a:2,e:"javac (compiler) source ko bytecode banata hai."},
{m:1,q:"JDK me kya-kya hota hai?",o:["Sirf JVM","JRE + development tools","Sirf libraries","Sirf compiler"],a:1,e:"JDK = JRE + development tools (jaise javac)."},
{m:1,q:"JRE kis se milkar banta hai?",o:["JVM + libraries","JDK + editor","Compiler + linker","Sirf JVM"],a:0,e:"JRE = JVM + runtime libraries."},
{m:1,q:"Java ko platform independent kya banata hai?",o:["Source code","Bytecode + JVM","Operating system","Hardware"],a:1,e:"Bytecode har platform ki JVM par chalta hai."},
{m:1,q:"WORA ka matlab kya hai?",o:["Write Once Run Anywhere","Work On Real Applications","Write Once Read Always","Windows Only Runtime Access"],a:0,e:"WORA = Write Once, Run Anywhere."},
{m:1,q:"Java me kitne primitive data types hote hain?",o:["6","7","8","10"],a:2,e:"8: byte, short, int, long, float, double, char, boolean."},
{m:1,q:"int data type kitni memory leta hai?",o:["2 bytes","4 bytes","8 bytes","1 byte"],a:1,e:"int 4 bytes (32-bit) ka hota hai."},
{m:1,q:"byte data type ki range kya hai?",o:["0 se 255","-128 se 127","-32768 se 32767","-256 se 255"],a:1,e:"byte 1 byte, range -128 se 127."},
{m:1,q:"long literal ke aage kaunsa suffix lagta hai?",o:["f","d","L","g"],a:2,e:"long ke liye L (jaise 100L)."},
{m:1,q:"float value ke aage kaunsa suffix lagta hai?",o:["f","L","d","s"],a:0,e:"float ke liye f (jaise 3.14f)."},
{m:1,q:"char data type kitni memory leta hai (Java me)?",o:["1 byte","2 bytes","4 bytes","8 bytes"],a:1,e:"char 2 bytes ka hota hai kyunki Java Unicode use karta hai."},
{m:1,q:"boolean type ki possible values kaunsi hain?",o:["0 aur 1","true aur false","yes aur no","on aur off"],a:1,e:"boolean sirf true ya false."},
{m:1,q:"int instance variable ki default value kya hoti hai?",o:["null","0","undefined","garbage"],a:1,e:"Numeric instance variable ki default value 0 hoti hai."},
{m:1,q:"Inme se primitive type NAHI hai?",o:["int","char","String","double"],a:2,e:"String ek class hai (non-primitive)."},
{m:1,q:"double kitni memory leta hai?",o:["4 bytes","8 bytes","2 bytes","16 bytes"],a:1,e:"double 8 bytes ka hota hai."},
{m:1,q:"Valid variable naam kaunsa hai?",o:["2name","my name","_count","class"],a:2,e:"Digit se start nahi, space nahi, keyword nahi. _count valid hai."},
{m:1,q:"5 / 2 ka result int me kya hoga?",o:["2.5","2","3","0"],a:1,e:"int division me decimal cut jaata hai, isliye 2."},
{m:1,q:"10 % 3 ka result kya hoga?",o:["3","0","1","3.33"],a:2,e:"% remainder deta hai; 10 me se 3 ka remainder 1."},
{m:1,q:"== operator kis category me aata hai?",o:["Arithmetic","Relational","Logical","Assignment"],a:1,e:"== relational (comparison) operator hai."},
{m:1,q:"Logical AND operator kaunsa hai?",o:["&","&&","|","and"],a:1,e:"&& logical AND hai."},
{m:1,q:"++ operator kis type ka hai?",o:["Binary","Unary","Ternary","Relational"],a:1,e:"++ ek unary operator hai (ek hi operand)."},
{m:1,q:"Inme se keyword kaunsa hai?",o:["number","salary","int","total"],a:2,e:"int Java ka reserved keyword hai."},

// ===== Module 2: I/O, Comments, Control Flow, Loops =====
{m:2,q:"User se input lene ke liye commonly kaunsi class use hoti hai?",o:["Printer","Scanner","Reader","Input"],a:1,e:"Scanner class input ke liye use hoti hai."},
{m:2,q:"Scanner class kis package me hoti hai?",o:["java.io","java.util","java.lang","java.scan"],a:1,e:"Scanner java.util package me hoti hai."},
{m:2,q:"println aur print me kya farak hai?",o:["Koi farak nahi","println ke baad next line par jaata hai","print next line par jaata hai","println fast hai"],a:1,e:"println output ke baad cursor next line par le jaata hai."},
{m:2,q:"int input padhne ke liye Scanner ka kaunsa method?",o:["nextLine()","next()","nextInt()","nextDouble()"],a:2,e:"nextInt() int value padhta hai."},
{m:2,q:"Poori line (spaces ke saath) padhne ke liye kaunsa method?",o:["next()","nextLine()","nextInt()","nextWord()"],a:1,e:"nextLine() poori line padhta hai."},
{m:2,q:"Single line comment kaise likhte hain?",o:["/* */","//","#","<!-- -->"],a:1,e:"// single-line comment hai."},
{m:2,q:"Multi-line comment ka syntax kya hai?",o:["// //","/* */","## ##","<> </>"],a:1,e:"/* ... */ multi-line comment hai."},
{m:2,q:"Documentation (Javadoc) comment kaisa hota hai?",o:["// ...","/* ... */","/** ... */","### ..."],a:2,e:"/** ... */ Javadoc documentation comment hai."},
{m:2,q:"Comments ko kaun ignore karta hai?",o:["Programmer","Compiler/JVM","User","Editor"],a:1,e:"Comments compile/execute nahi hote, ignore hote hain."},
{m:2,q:"switch me har case ke baad kya lagana zaroori hai (fall-through rokne ke liye)?",o:["continue","break","return","stop"],a:1,e:"break na ho to fall-through hota hai."},
{m:2,q:"switch me koi case match na ho to kaunsa block chalta hai?",o:["else","default","final","catch"],a:1,e:"default block tab chalta hai jab koi case match na ho."},
{m:2,q:"Kaunsa loop kam se kam ek baar zaroor chalta hai?",o:["for","while","do-while","for-each"],a:2,e:"do-while pehle body chalata hai phir condition check karta hai."},
{m:2,q:"while loop kis type ka hai?",o:["Exit-controlled","Entry-controlled","Hamesha infinite","Reverse"],a:1,e:"while pehle condition check karta hai (entry-controlled)."},
{m:2,q:"for loop ka sahi syntax kaunsa hai?",o:["for(init; update; condition)","for(condition; init; update)","for(init; condition; update)","for(update; condition; init)"],a:2,e:"for(initialization; condition; update)."},
{m:2,q:"break statement loop me kya karta hai?",o:["Ek iteration skip karta hai","Poora loop turant band karta hai","Loop restart karta hai","Kuch nahi"],a:1,e:"break loop ko turant terminate kar deta hai."},
{m:2,q:"continue statement kya karta hai?",o:["Loop band karta hai","Current iteration skip karke agli par jaata hai","Program band karta hai","Case skip karta hai"],a:1,e:"continue current iteration skip karta hai."},
{m:2,q:"if(condition) me condition ka result kaisa hona chahiye?",o:["int","boolean (true/false)","String","char"],a:1,e:"if ki condition boolean honi chahiye."},
{m:2,q:"Ternary operator ka syntax kya hai?",o:["condition ? a : b","condition : a ? b","a ? b : condition","if a else b"],a:0,e:"condition ? true_value : false_value."},
{m:2,q:"Ek variable ki bahut saari values check karni ho to best kya hai?",o:["for","switch","while","do-while"],a:1,e:"switch multiple fixed values ke liye saaf rehta hai."},
{m:2,q:"Nested loop kya hai?",o:["Do alag loops","Ek loop ke andar dusra loop","Loop bina condition","Ulta loop"],a:1,e:"Loop ke andar loop = nested loop."},
{m:2,q:"for me infinite loop kab banta hai?",o:["Jab condition kabhi false na ho","Jab init galat ho","Jab break ho","Kabhi nahi"],a:0,e:"Condition hamesha true rahe to loop kabhi nahi rukta."},
{m:2,q:"System.out.print(\"A\"); System.out.println(\"B\"); ka output?",o:["A phir nayi line par B","AB","A B","B A"],a:1,e:"print newline nahi deta, dono ek hi line me: AB."},
{m:2,q:"for-each loop mainly kis liye use hota hai?",o:["Index badalne","Array/collection traverse karne","Condition banane","Input lene"],a:1,e:"for-each se aasani se elements ghoomte hain."},
{m:2,q:"Scanner object banane ka sahi tarika kaunsa hai?",o:["Scanner sc = new Scanner();","Scanner sc = new Scanner(System.in);","Scanner sc = Scanner(System.in);","new Scanner sc;"],a:1,e:"new Scanner(System.in) sahi hai."},
{m:2,q:"nextInt() ke turant baad nextLine() par kya common problem?",o:["Koi problem nahi","nextLine() skip ho jaata hai","Program band ho jaata hai","int null ho jaata hai"],a:1,e:"Bacha hua newline nextLine() ko skip kara deta hai."},
{m:2,q:"Comments code me kyun likhte hain?",o:["Speed badhane","Code explain/document karne","Memory ke liye","Compile ke liye"],a:1,e:"Comments readability/documentation ke liye hote hain."},

// ===== Module 3: Methods & Parameter Passing =====
{m:3,q:"Method banane ka main fayda kya hai?",o:["Program slow karna","Code reusability","Memory badhana","Errors badhana"],a:1,e:"Method se code reuse hota hai."},
{m:3,q:"Jo method kuch return na kare uska return type kya hota hai?",o:["null","void","empty","0"],a:1,e:"void = kuch return nahi karta."},
{m:3,q:"Method definition me diye gaye variables ko kya kehte hain?",o:["Arguments","Parameters","Values","Returns"],a:1,e:"Definition me = parameters (placeholder)."},
{m:3,q:"Method call karte waqt di gayi actual values ko kya kehte hain?",o:["Parameters","Arguments","Fields","Locals"],a:1,e:"Call me di gayi values = arguments."},
{m:3,q:"Method overloading kis par based hoti hai?",o:["Sirf return type","Alag parameters (number/type)","Sirf naam","Access modifier"],a:1,e:"Overloading me parameters alag hone chahiye."},
{m:3,q:"Sirf return type alag hone se overloading hoti hai?",o:["Haan","Nahi","Kabhi kabhi","Sirf static me"],a:1,e:"Sirf return type kaafi nahi; parameters alag hone chahiye."},
{m:3,q:"Java me parameter passing kaise hota hai?",o:["Pass by reference","Pass by value","Pass by pointer","Pass by name"],a:1,e:"Java hamesha pass-by-value hai."},
{m:3,q:"Primitive variable method ko pass karne par original par kya asar?",o:["Badal jaata hai","Koi asar nahi (copy jaati hai)","Delete hota hai","Null ho jaata hai"],a:1,e:"Primitive ki copy jaati hai, original safe rehta hai."},
{m:3,q:"Array method ko pass karke uska element badla jaaye to original array?",o:["Badal jaata hai","Nahi badalta","Error aata hai","Copy ban jaata hai"],a:0,e:"Reference ki copy jaati hai, isliye actual object me change dikhta hai."},
{m:3,q:"return statement ka kaam kya hai?",o:["Loop todna","Value wapas dena aur method se bahar aana","Print karna","Input lena"],a:1,e:"return value deta hai aur method se bahar aata hai."},
{m:3,q:"void method me sirf 'return;' likh sakte hain?",o:["Nahi","Haan, bina value ke method se bahar aane ke liye","Sirf error ke saath","Sirf loop me"],a:1,e:"void me return; se jaldi bahar aa sakte hain."},
{m:3,q:"static method ko object banaye bina kaise call karte hain?",o:["object.method()","ClassName.method()","new method()","method(this)"],a:1,e:"ClassName.method() se static call hota hai."},
{m:3,q:"Method naam likhne ki convention kya hai?",o:["PascalCase","camelCase","ALL_CAPS","snake_case"],a:1,e:"Methods camelCase me likhte hain."},
{m:3,q:"public static int add(int a,int b) me return type kya hai?",o:["public","static","int","add"],a:2,e:"int hi return type hai."},
{m:3,q:"Ek method dusre method ko call kar sakta hai?",o:["Nahi","Haan","Sirf main","Sirf static"],a:1,e:"Haan, ek method dusre ko call kar sakta hai."},
{m:3,q:"Recursion kya hai?",o:["Method khud ko call kare","Do method ek saath","Ek loop","Overloading"],a:0,e:"Method ka khud ko call karna = recursion."},
{m:3,q:"Method signature me kya include hota hai?",o:["Method naam + parameters","Sirf return type","Sirf body","Comments"],a:0,e:"Signature = naam + parameter list."},
{m:3,q:"add(10,20) me 10 aur 20 kya hain?",o:["Parameters","Arguments","Return values","Types"],a:1,e:"Call ke time di gayi values = arguments."},
{m:3,q:"void ka matlab kya hai?",o:["Method value return karega","Method kuch return nahi karega","Method static hai","Method private hai"],a:1,e:"void = no return value."},
{m:3,q:"Local variable ka scope kya hota hai?",o:["Poore program me","Sirf us method ke andar","Sirf class me","Global"],a:1,e:"Local variable sirf apne method me valid hai."},
{m:3,q:"Kaunsa method overloading ka valid example hai?",o:["int f() aur int f()","int f(int) aur int f(int,int)","int f() aur void f() same params","Koi nahi"],a:1,e:"Alag parameter count = valid overloading."},
{m:3,q:"Method call karne ke liye kya use karte hain?",o:["Method ka naam + ()","Sirf class naam","new keyword","return"],a:0,e:"methodName(arguments) se call hota hai."},
{m:3,q:"parameter list khaali ho to method?",o:["Galat hai","Bina input ke chalta hai","Error deta hai","Static ban jaata hai"],a:1,e:"No-arg method bilkul valid hai."},
{m:3,q:"Objects ke saath pass-by-value me kya copy hoti hai?",o:["Poora object","Reference (address) ki copy","Kuch nahi","Sirf naam"],a:1,e:"Object ka reference copy hota hai."},
{m:3,q:"return type aur returned value match na kare to?",o:["Chal jaata hai","Compile error","Sirf warning","Runtime me theek"],a:1,e:"Type mismatch par compile error aata hai."},

// ===== Module 4: Arrays & Strings =====
{m:4,q:"Array me elements kaise hote hain?",o:["Alag-alag types","Same data type","Sirf int","Sirf String"],a:1,e:"Array me same type ke elements hote hain."},
{m:4,q:"Array ka index kis number se shuru hota hai?",o:["1","0","-1","depends"],a:1,e:"Index 0 se shuru hota hai."},
{m:4,q:"5 size ke array me valid index range?",o:["0 se 5","1 se 5","0 se 4","1 se 4"],a:2,e:"5 elements = index 0 se 4."},
{m:4,q:"Array ka size kaise milta hai?",o:["arr.size()","arr.length()","arr.length","len(arr)"],a:2,e:"Array me length ek property hai (bina bracket)."},
{m:4,q:"String ki length kaise milti hai?",o:["s.length","s.size()","s.length()","len(s)"],a:2,e:"String me length() ek method hai (bracket ke saath)."},
{m:4,q:"int[] a = new int[3]; me default values kya hongi?",o:["null","0","garbage","1"],a:1,e:"int array default 0 se bharta hai."},
{m:4,q:"Galat index access karne par kaunsa exception?",o:["NullPointerException","ArrayIndexOutOfBoundsException","NumberFormatException","IOException"],a:1,e:"Out-of-range index = ArrayIndexOutOfBoundsException."},
{m:4,q:"2D array kaise declare karte hain?",o:["int a[]","int a[][]","int a{}","int[] a()"],a:1,e:"int a[][] = 2D array."},
{m:4,q:"int[][] m = {{1,2},{3,4}}; me m[1][0] kya hai?",o:["1","2","3","4"],a:2,e:"Row 1 (second row) ka index 0 = 3."},
{m:4,q:"Array ka size set hone ke baad?",o:["Badal sakta hai","Fixed rehta hai","Auto badhta hai","Zero ho jaata hai"],a:1,e:"Array ka size fixed hota hai."},
{m:4,q:"String Java me kya hai?",o:["primitive type","ek class (object)","keyword","method"],a:1,e:"String ek class (non-primitive) hai."},
{m:4,q:"String immutable hone ka matlab?",o:["Badla ja sakta hai","Ek baar bana to badla nahi ja sakta","Sirf padha jaata","Delete nahi hota"],a:1,e:"Immutable = value change nahi hoti, naya object banta hai."},
{m:4,q:"Baar-baar change hone wali string ke liye kya use karte hain?",o:["String","StringBuilder","char","int"],a:1,e:"StringBuilder mutable hai, changes ke liye behtar."},
{m:4,q:"String content compare karne ka sahi tarika?",o:["==","=","equals()","compare"],a:2,e:".equals() content compare karta hai."},
{m:4,q:"== do String par kya compare karta hai?",o:["Content","Reference (address)","Length","Case"],a:1,e:"== reference (address) compare karta hai."},
{m:4,q:"\"Hello\".charAt(1) kya dega?",o:["'H'","'e'","'l'","'o'"],a:1,e:"Index 1 par 'e' hai."},
{m:4,q:"\"Hello\".length() kya dega?",o:["4","5","6","0"],a:1,e:"Hello me 5 characters hain."},
{m:4,q:"\"Hello\".substring(0,3) kya dega?",o:["\"Hel\"","\"Hell\"","\"ell\"","\"Hello\""],a:0,e:"substring(0,3) index 0,1,2 leta hai = Hel."},
{m:4,q:"toUpperCase() kya karta hai?",o:["Chhote akshar","Bade akshar me badle","Reverse","Trim"],a:1,e:"Sabhi letters capital kar deta hai."},
{m:4,q:"trim() method kya karta hai?",o:["Case badalta","Aage-peeche ke spaces hatata","String todta","Length deta"],a:1,e:"trim() leading/trailing spaces hatata hai."},
{m:4,q:"Do String jodne ke liye kaunsa operator?",o:["-","+","*","&"],a:1,e:"+ se strings concatenate hoti hain."},
{m:4,q:"String s = \"Hi\"; kaunsa tarika hai?",o:["new object","String literal","char array","method call"],a:1,e:"Ye String literal way hai."},
{m:4,q:"\"Hello\".indexOf('l') kya dega?",o:["1","2","3","4"],a:1,e:"Pehla 'l' index 2 par hai."},
{m:4,q:"for-each se array traverse karna kab acha hai?",o:["Jab index badalna ho","Jab sirf values chahiye","Jab size badalna ho","Kabhi nahi"],a:1,e:"Jab sirf values padhni ho tab for-each best."},
{m:4,q:"String immutable isliye toUpperCase() jaise method kya karte hain?",o:["Same string badalte","Naya string return karte","Error dete","null dete"],a:1,e:"Naya string banake return karte hain, original same."},

// ===== Module 5: Classes, Objects, Constructors & this =====
{m:5,q:"Class kya hai?",o:["Real object","Blueprint/design","Variable","Method"],a:1,e:"Class ek blueprint hai jisse objects bante hain."},
{m:5,q:"Object kya hai?",o:["Design","Class ka real instance","Keyword","Loop"],a:1,e:"Object class ka real instance hai."},
{m:5,q:"Object banane ke liye kaunsa keyword use hota hai?",o:["class","new","this","void"],a:1,e:"new se object banta hai."},
{m:5,q:"Ek class se kitne object ban sakte hain?",o:["Sirf 1","Do","Jitne chahe","Zero"],a:2,e:"Ek class se jitne chahe objects bante hain."},
{m:5,q:"Constructor ka naam kaisa hota hai?",o:["Kuch bhi","Class ke naam jaisa","main","new"],a:1,e:"Constructor ka naam class ke naam jaisa hota hai."},
{m:5,q:"Constructor ka return type kya hota hai?",o:["void","int","koi return type nahi","String"],a:2,e:"Constructor ka koi return type nahi hota, void bhi nahi."},
{m:5,q:"Constructor kab call hota hai?",o:["Manually","Object bante hi automatically","Program end par","Kabhi nahi"],a:1,e:"new se object bante hi constructor auto-call hota hai."},
{m:5,q:"Agar koi constructor na banayein to?",o:["Error aata hai","Java default constructor deta hai","Object nahi banta","Class delete hoti"],a:1,e:"Java khud ek default constructor de deta hai."},
{m:5,q:"Bina parameter wale constructor ko kya kehte hain?",o:["Parameterized","Default/no-arg","Copy","Static"],a:1,e:"No-arg (default) constructor."},
{m:5,q:"Values pass karne wale constructor ko kya kehte hain?",o:["Default","Parameterized","Empty","Copy"],a:1,e:"Parameterized constructor values leta hai."},
{m:5,q:"Ek object ki values naye object me copy karne wala constructor?",o:["Default","Copy constructor","Static","Parameterized"],a:1,e:"Copy constructor purane object se values copy karta hai."},
{m:5,q:"Constructor overloading kya hai?",o:["Ek hi constructor","Alag parameters wale multiple constructors","Do class","Ek method"],a:1,e:"Same class me alag parameters wale constructors."},
{m:5,q:"this keyword kis ko point karta hai?",o:["Class ko","Current object ko","Parent ko","main ko"],a:1,e:"this current object ka reference hai."},
{m:5,q:"this ka sabse common use kya hai?",o:["Loop","Instance var aur parameter ke naam clash solve karna","Print karna","Input"],a:1,e:"this.var = var naming clash solve karta hai."},
{m:5,q:"this.name = name; me this.name kya hai?",o:["Parameter","Instance (object) variable","Local var","Static var"],a:1,e:"this.name object ka instance variable hai."},
{m:5,q:"this() ka use kya hai?",o:["Method call","Same class ke dusre constructor ko call","Object delete","Loop"],a:1,e:"this() se ek constructor dusre ko call karta hai."},
{m:5,q:"Constructor aur method me ek bada farak?",o:["Constructor ka return type nahi hota","Method ka naam class jaisa","Constructor manually call hota","Koi farak nahi"],a:0,e:"Constructor ka koi return type nahi hota."},
{m:5,q:"new keyword memory kaha allocate karta hai?",o:["Stack","Heap","Register","Disk"],a:1,e:"Object heap memory me banta hai."},
{m:5,q:"c1.colour = \"Red\"; me colour kya hai?",o:["Method","Object ki property/field","Class","Constructor"],a:1,e:"colour object ki property (field) hai."},
{m:5,q:"Object ke method ko kaise call karte hain?",o:["ClassName.method()","object.method()","new method()","this()"],a:1,e:"object.method() se instance method call hota hai."},
{m:5,q:"Ek class me kitne constructor ho sakte hain?",o:["Sirf 1","Ek se zyada (overloaded)","Zero always","Fixed 2"],a:1,e:"Overloading se multiple constructors ban sakte hain."},
{m:5,q:"Instance variable kis ka hota hai?",o:["Class ka (shared)","Har object ka apna","Method ka","Global"],a:1,e:"Instance variable har object ka alag hota hai."},
{m:5,q:"OOP ka full form kya hai?",o:["Object Oriented Programming","Only One Program","Open Office Program","Ordered Object Process"],a:0,e:"OOP = Object Oriented Programming."},
{m:5,q:"Object create hone par sabse pehle kya chalta hai?",o:["main","Constructor","toString","finalize"],a:1,e:"Object bante hi constructor chalta hai."},
{m:5,q:"Class ke andar properties + methods kya represent karte hain?",o:["Data + behaviour","Sirf data","Sirf behaviour","Kuch nahi"],a:0,e:"Properties = data, methods = behaviour."},

// ===== Module 6: Static Members & Blocks =====
{m:6,q:"static member kis ka hota hai?",o:["Har object ka alag","Class ka (shared)","Method ka","Local"],a:1,e:"static member class ka hota hai, sabme shared."},
{m:6,q:"static variable ki kitni copy banti hai?",o:["Har object ki alag","Sirf ek (shared)","Do","Zero"],a:1,e:"static variable ki sirf ek shared copy hoti hai."},
{m:6,q:"static member ko access karne ka best tarika?",o:["object.member","ClassName.member","new member","this.member"],a:1,e:"ClassName.member se access karte hain."},
{m:6,q:"main method static kyun hota hai?",o:["Fast chale","JVM object banaye bina call kar sake","Memory bache","Rule nahi hai"],a:1,e:"JVM bina object banaye main() call kar paata hai."},
{m:6,q:"static method me kya directly use NAHI kar sakte?",o:["static variable","non-static (instance) variable","local variable","parameter"],a:1,e:"Static method me instance member aur this directly nahi."},
{m:6,q:"static method me this keyword?",o:["Use kar sakte","Use nahi kar sakte","Zaroori hai","Auto banta"],a:1,e:"Static ka koi object nahi, isliye this allowed nahi."},
{m:6,q:"static block kab chalta hai?",o:["main ke baad","Class load hote hi (main se pehle), ek baar","Har object par","Kabhi nahi"],a:1,e:"Static block class load par ek baar chalta hai."},
{m:6,q:"static block ka use kya hai?",o:["Object banana","static variables initialize karna","Loop","Input"],a:1,e:"Static block static variables ko set karta hai."},
{m:6,q:"Object count karne ke liye best kya hai?",o:["instance variable","static variable (constructor me ++)","local variable","final variable"],a:1,e:"Static variable sab objects me shared hota hai, count ke liye best."},
{m:6,q:"static keyword bina object ke access allow karta hai?",o:["Haan","Nahi","Sirf private","Sirf main"],a:0,e:"Static member object ke bina access ho jaata hai."},
{m:6,q:"Math.sqrt() jaisa call kis baat ka example hai?",o:["Instance method","static method","Constructor","Field"],a:1,e:"Math.sqrt() ek static method call hai."},
{m:6,q:"static variable ko memory kab milti hai?",o:["Object banne par","Class load hone par","Program end par","Method call par"],a:1,e:"Static variable class load ke waqt memory paata hai."},
{m:6,q:"Ek object static variable badle to baaki objects me?",o:["Nahi dikhega","Sabme change dikhega","Error","Copy banegi"],a:1,e:"Static shared hai, isliye sabke liye badal jaata hai."},
{m:6,q:"static method directly kis ko access kar sakta hai?",o:["Sirf non-static","Sirf static members","Dono aasani se","Kuch nahi"],a:1,e:"Static method sirf static members ko direct use karta hai."},
{m:6,q:"static block kitni baar chalta hai?",o:["Har object par","Sirf ek baar (class load par)","Do baar","Har call par"],a:1,e:"Sirf ek baar, class load ke waqt."},
{m:6,q:"static ka ulta (har object ka apna) kya kehte hain?",o:["global","instance (non-static)","local","final"],a:1,e:"Non-static = instance member (har object ka apna)."},
{m:6,q:"static final variable aksar kya represent karta hai?",o:["Variable","Constant","Method","Object"],a:1,e:"static final = constant (fixed value)."},
{m:6,q:"public static void main me void kya batata hai?",o:["main value return karega","main kuch return nahi karega","main static hai","main public hai"],a:1,e:"void = main kuch return nahi karta."},
{m:6,q:"static method me instance member chahiye to?",o:["Direct use karo","Object bana kar access karo","Error","this use karo"],a:1,e:"Object banakar hi instance member access hoga."},
{m:6,q:"Class ka data sabhi objects me common rakhna ho to?",o:["instance variable","static variable","local variable","parameter"],a:1,e:"Static variable sabme common data rakhta hai."},
{m:6,q:"static method call ke liye object zaroori hai?",o:["Haan","Nahi","Kabhi kabhi","Sirf private"],a:1,e:"Static method ke liye object zaroori nahi."},
{m:6,q:"ClassName.staticMethod() valid hai?",o:["Nahi","Haan","Sirf main me","Sirf loop me"],a:1,e:"Haan, ye static call ka sahi tarika hai."},
{m:6,q:"static variable ko instance variable keh sakte?",o:["Haan","Nahi (ye class variable hai)","Same cheez","Sirf static block me"],a:1,e:"Static variable = class variable, instance nahi."},
{m:6,q:"Static block aur constructor me pehle kaun chalega?",o:["Constructor","Static block","Dono saath","main"],a:1,e:"Static block class load par, constructor object banne par — static block pehle."},
{m:6,q:"static ka overall matlab kya hai?",o:["Object-specific","Class-level (shared)","Temporary","Private"],a:1,e:"static = class-level, shared across all objects."}
];
